apiVersion: v1
kind: Service
metadata:
  name: {{ include "oj.fullname" . }}-app
spec:
  selector:
    app: {{ include "oj.name" . }}-app
  ports:
    - port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    app: redis
  ports:
    - port: 6379
